spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: dearmoment
  profiles:
    default: local
  mail:
    host: smtp.gmail.com
    port: 587
    receiver: ${MAIL_RECEIVER}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000
