object-storage:
  bucket-name: ${OBJECT_STORAGE_BUCKET_NAME}
  config-path: ${OBJECT_STORAGE_CONFIG_PATH}
  namespace-name: ${OBJECT_STORAGE_NAMESPACE_NAME}
  photo-image-dir: ${OBJECT_STORAGE_IMAGE_DIR}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}

sentry:
  dsn: "${SENTRY_DSN}"
  exception-resolver-order: -2147483647
  max-request-body-size: always
  send-default-pii: true
  traces-sample-rate: 1.0

oracle:
  net:
    authentication_services: SSL
    ssl_version: "1.2"
    ssl_server_dn_match: true
