name: ci
on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      #빌드 시간 향상
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create OCI Config File
        run: |
          mkdir -p ~/.oci
          echo "${{ secrets.OBJECT_STORAGE_CONFIG }}" > ~/.oci/config
          chmod 600 ~/.oci/config

      - name: Create Private Key File
        run: |
          echo "${{ secrets.OBJECT_STORAGE_PRIVATE_KEY }}" > ~/.oci/private_key.pem
          chmod 600 ~/.oci/private_key.pem

      - name: Set environment variables
        env:
          MAIL_RECEIVER: ${{ secrets.MAIL_RECEIVER }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}

      # Gradle 빌드 실행
      - name: Build with Gradle
        run: ./gradlew build
