name: Deploy to Production

on:
  workflow_run:
    workflows: ["Docker Publish"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_IP }}               # 배포 대상 서버의 공인 IP (예: OCI VM)
          username: ${{ secrets.SERVER_USER }}           # 서버 접속 사용자 (예: ubuntu)
          key: ${{ secrets.SSH_PRIVATE_KEY }}            # SSH 개인 키 (GitHub Secrets 에 등록)
          script: |
            echo "Pulling latest Docker image from GHCR..."
            docker pull ghcr.io/${{ github.repository }}/dear-moment-backend:latest

            echo "Stopping existing container (if any)..."
            docker stop dear-moment-backend || true
            docker rm dear-moment-backend || true

            echo "Starting new container..."
            docker run -d --restart=always -p 8080:8080 \
              -v /home/ubuntu/adb_wallet:/app/wallet:ro \
              -e TNS_ADMIN=/app/wallet \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              --name dear-moment-backend \
              ghcr.io/${{ github.repository }}/dear-moment-backend:latest
