name: Setup OCI Config
on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Create OCI Config File
        run: |
          mkdir -p ~/.oci
          echo "${{ secrets.OBJECT_STORAGE_CONFIG }}" > ~/.oci/config
          chmod 600 ~/.oci/config

      - name: Create Private Key File
        run: |
          echo "${{ secrets.OBJECT_STORAGE_PRIVATE_KEY }}" > ~/.oci/private_key.pem
          chmod 600 ~/.oci/private_key.pem
